---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---


## Loading and preprocessing the data
activity <- read.csv("./activity/activity.csv")
dim(activity)

# Identify class of variables in the data
str(activity)

# Convert class 0f date variable to "Date"
# and steps & interval to numeric
activity$date <- as.Date(activity$date)
activity$steps <- as.numeric(activity$steps)
activity$interval <- as.numeric(activity$interval)

## What is mean total number of steps taken per day?

activityDay <- aggregate(steps ~ date, data=activity, FUN= sum)
plot(activityDay$date, activityDay$steps, type="h", xlab="Day", ylab="Steps", main="Total number of steps per day")
mean(activityDay$steps)
median(activityDay$steps)


## What is the average daily activity pattern?
activityInterval <- aggregate(steps ~ interval, data=activity, FUN= mean)
plot(activityInterval$interval, activityInterval$steps, type="l", xlab="Minutes", ylab="Average steps", main="Average steps per 5 minutes interval")

activityInterval[activityInterval$steps == max(activityInterval$steps),]$interval


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
